#!/bin/sh
#
# nmosnode        Starts nmosnode.
#

umask 077

start() {
        printf "Starting nmosnode: "
        /usr/bin/nmosnode
        touch /var/lock/nmosnode
        echo "OK"
}
stop() {
        printf "Stopping nmosnode: "
        killall nmosnode
        rm -f /var/lock/nmodnode
        echo "OK"
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?